baseURL = "https://anakaiti.net/"
languageCode = "en-us"
title = "Anakaiti"
theme = "pulp"

[params]
    author = "Yahya H"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        We'll see creation come undone
        These bones that bound us will be gone
        We'll stir our spirits 'til we're one
        Then soft as shadows we'll become
    """
    publicationYear = "2019"

[outputs]
    section = ["JSON", "HTML"]


[[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/mohdyahyahrln/"
    weight = 10

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/anakaiti"
    weight = 20

[[menu.main]]
    identifier = "keybase"
    name = "Keybase"
    pre = "<i class='fab fa-keybase fa-lg'></i>"
    url = "https://keybase.io/anakaiti"
    weight = 20
