baseURL = "https://anakaiti.net/"
languageCode = "en-us"
title = "Anakaiti"
theme = "pulp"
pygmentsCodefences = true
pygmentsUseClasses = true

[params]
    author = "Yahya H"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        I turn coffee into YAML and questionable shell scripts.
    """
    publicationYear = "2019"
    custom_css = ["/css/custom.css"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "posts"
    pre = "<i class='fa fa-book-open fa-lg'></i>"
    url = "posts/"
    weight = 10

[[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/mohdyahyahrln/"
    weight = 20

[[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/anakaiti"
    weight = 30

[[menu.main]]
    identifier = "keybase"
    pre = "<i class='fab fa-keybase fa-lg'></i>"
    url = "https://keybase.io/anakaiti"
    weight = 40
